### ISSUE TITLE
must use ruby >= 2.5 for special reason?

### ISSUE THREAD

**Issue by tianlu1677** [vfreefly/kimurai#2]
I want to use this gem on my project but my project use ruby 2.4.1. Any special reason? depend gems or special ruby syntax rules？

**Comment by vfreefly** [comment]
Hello @tianlu1677 !

Yes, in some places Kimurai uses new Ruby 2.5 syntax, like `Rescue in do/end blocks` or `slice` method. It's easy to fix and change minimal supported version to 2.4. But first can I ask you how do you plan to use gem with your project? Run crawlers from Rails using background jobs (Sidekiq for example)?

_Currently_ the only correct way to run crawler is to run it in separate process. One process - one crawler. Crawler finished - process stops. Otherwise things will go wrong (because 1. Kimurai uses class variables to store stats (requests/items) between all possible threads 2. [at_exit](https://ruby-doc.org/core-2.5.1/Kernel.html#method-i-at_exit) uses to execute `at_stop` crawler callback). 

I have plans to add support to run multiple crawlers multiple times from a single Ruby process, but it should be well tested before release.

This was a reason why I choosed to use 2.5.0 version from the begining because Kimurai is not designed (yet) to use it as part of other existing application (so it makes sence to use a fresh Ruby for Kimurai crawlers).
